# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(488, 391)
        Form.setWindowOpacity(0.8)
        Form.setStyleSheet("background-color: rgb(21, 25, 31);\n"
"font: \"Copperplate Gothic Light\";")
        self.Window = QtWidgets.QWidget(Form)
        self.Window.setGeometry(QtCore.QRect(0, 20, 491, 351))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.Window.setFont(font)
        self.Window.setObjectName("Window")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Window)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Image_2 = QtWidgets.QWidget(self.Window)
        self.Image_2.setObjectName("Image_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Image_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_5 = QtWidgets.QWidget(self.Image_2)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_6.addWidget(self.widget_5)
        self.label_4 = QtWidgets.QLabel(self.Image_2)
        self.label_4.setMaximumSize(QtCore.QSize(61, 61))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/user.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.widget_6 = QtWidgets.QWidget(self.Image_2)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6.addWidget(self.widget_6)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.Image_2)
        self.Logpass_2 = QtWidgets.QWidget(self.Window)
        self.Logpass_2.setObjectName("Logpass_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Logpass_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_7 = QtWidgets.QWidget(self.Logpass_2)
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.emailLine = QtWidgets.QLineEdit(self.widget_7)
        self.emailLine.setGeometry(QtCore.QRect(120, 10, 321, 35))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.emailLine.setFont(font)
        self.emailLine.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(79, 117, 145) ;\n"
"color: #FFF;\n"
"border-radius: 15px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"padding-bottom: 4px;\n"
"}")
        self.emailLine.setObjectName("emailLine")
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 46, 15))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.Logpass_2)
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.label_6 = QtWidgets.QLabel(self.widget_8)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_6.setObjectName("label_6")
        self.passwordLine = QtWidgets.QLineEdit(self.widget_8)
        self.passwordLine.setGeometry(QtCore.QRect(120, 10, 321, 35))
        self.passwordLine.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(79, 117, 145) ;\n"
"color: #FFF;\n"
"border-radius: 15px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"padding-bottom: 4px;\n"
"}")
        self.passwordLine.setObjectName("passwordLine")
        self.verticalLayout_4.addWidget(self.widget_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addWidget(self.Logpass_2)
        self.Remember_2 = QtWidgets.QWidget(self.Window)
        self.Remember_2.setMaximumSize(QtCore.QSize(451, 90))
        self.Remember_2.setObjectName("Remember_2")
        self.rememverMeChecker = QtWidgets.QCheckBox(self.Remember_2)
        self.rememverMeChecker.setGeometry(QtCore.QRect(30, 30, 151, 24))
        self.rememverMeChecker.setStyleSheet("QCheckBox{\n"
"color: rgb(202, 206, 216);\n"
"font-size: 14px;\n"
"font: \"Copperplate Gothic Light\";\n"
"}\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"border : 2px solid rgb(79, 117, 145);\n"
"width : 20px;\n"
"height : 20px;\n"
"border-radius : 10px;\n"
"}\n"
"\n"
"\n"
"QCheckBox::hover {\n"
"    color: #9ebad6\n"
"}\n"
"\n"
"\n"
"QCheckBox::hover::checked {\n"
"    border: solid #232933;\n"
"}\n"
"/*\n"
"QCheckBox:hover::unchecked {\n"
"    border: solid rgb(79, 117, 145);\n"
"}\n"
"\n"
"\n"
"QCheckBox:indicator: {\n"
"    border: 4px\n"
"}\n"
"\n"
"QCheckBox:indicator:unchecked:hover {\n"
"    color:#576e84\n"
"}\n"
"*/\n"
"\n"
"QCheckBox::indicator::checked\n"
"{\n"
"    image: url(:/Pngs/Assets/ICLight/check.png);\n"
"}\n"
"")
        self.rememverMeChecker.setObjectName("rememverMeChecker")
        self.AuthLoginButton = QtWidgets.QPushButton(self.Remember_2)
        self.AuthLoginButton.setGeometry(QtCore.QRect(280, 30, 141, 41))
        self.AuthLoginButton.setStyleSheet("QPushButton {\n"
"    color: rgb(166, 177, 211);\n"
"    background-color: rgb(38, 45, 58);\n"
"    border-left: 1px solid rgb(57, 79, 100);\n"
"    border-right: 1px solid rgb(51, 54, 60);    \n"
"    border-bottom: 3px solid rgb(28, 31, 46);\n"
"\n"
"    font-size: 14px;\n"
"    font: \"Copperplate Gothic Light\";\n"
"\n"
"    border-radius: 10px\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(25, 45, 64);\n"
"    border-left: 2px solid rgb(37, 46, 53);\n"
"    border-right: 2px solid rgb(31, 34, 40);    \n"
"    border-bottom: 3px solid rgb(18, 21, 26);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(20, 25, 34);\n"
"    border-left: 2px solid rgb(5, 26, 33);\n"
"    border-right: 2px solid rgb(5, 24, 30);    \n"
"    border-bottom: 3px solid rgb(5, 21, 26);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/corner-down-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AuthLoginButton.setIcon(icon)
        self.AuthLoginButton.setObjectName("AuthLoginButton")
        self.authErrorLaber = QtWidgets.QLabel(self.Remember_2)
        self.authErrorLaber.setGeometry(QtCore.QRect(34, 0, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.authErrorLaber.setFont(font)
        self.authErrorLaber.setStyleSheet("color: rgb(250, 100, 100);\n"
"font-size: 14px;")
        self.authErrorLaber.setText("")
        self.authErrorLaber.setAlignment(QtCore.Qt.AlignCenter)
        self.authErrorLaber.setObjectName("authErrorLaber")
        self.verticalLayout_3.addWidget(self.Remember_2)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 501, 31))
        self.widget_2.setStyleSheet("background-color: rgb(35, 41, 51);")
        self.widget_2.setObjectName("widget_2")
        self.widget_9 = QtWidgets.QWidget(self.widget_2)
        self.widget_9.setGeometry(QtCore.QRect(390, -10, 101, 51))
        self.widget_9.setStyleSheet("QPushButton {\n"
"    border: 2px solid transparent;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: rgb(20, 25, 34);\n"
"}")
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.authCollapseButton = QtWidgets.QPushButton(self.widget_9)
        self.authCollapseButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.authCollapseButton.setIcon(icon1)
        self.authCollapseButton.setIconSize(QtCore.QSize(22, 22))
        self.authCollapseButton.setObjectName("authCollapseButton")
        self.horizontalLayout_2.addWidget(self.authCollapseButton)
        self.authCloseButton = QtWidgets.QPushButton(self.widget_9)
        self.authCloseButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.authCloseButton.setIcon(icon2)
        self.authCloseButton.setIconSize(QtCore.QSize(22, 22))
        self.authCloseButton.setObjectName("authCloseButton")
        self.horizontalLayout_2.addWidget(self.authCloseButton)
        self.authCloseButton.raise_()
        self.authCollapseButton.raise_()
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 131, 18))
        self.label_2.setStyleSheet("color: rgb(145, 160, 187);\n"
"font: \"Copperplate Gothic Light\";\n"
"font-size: 14px;")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.widget_9.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.emailLine.setPlaceholderText(_translate("Form", "Введите ваш адрес электронной почты"))
        self.label_5.setText(_translate("Form", "Email:"))
        self.label_6.setText(_translate("Form", "Пароль:"))
        self.passwordLine.setPlaceholderText(_translate("Form", "Введите ваш пароль от электронной почты"))
        self.rememverMeChecker.setText(_translate("Form", "Запомнить меня"))
        self.AuthLoginButton.setText(_translate("Form", "Войти"))
        self.label_2.setText(_translate("Form", "Авторизация"))
import auto_res_rc
