# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LetterSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(765, 697)
        Form.setStyleSheet("font: \"Copperplate Gothic Light\";\n"
"background-color: rgb(21, 25, 31);")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 40, 745, 311))
        self.widget.setObjectName("widget")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 121, 24))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 18px;\n"
"font: \"Copperplate Gothic Light\";")
        self.label_9.setObjectName("label_9")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 721, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_6 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.WordsInSubjectLine = QtWidgets.QLineEdit(self.widget_6)
        self.WordsInSubjectLine.setMinimumSize(QtCore.QSize(0, 21))
        self.WordsInSubjectLine.setMaximumSize(QtCore.QSize(16777215, 31))
        self.WordsInSubjectLine.setStyleSheet("QLineEdit{\n"
"border: 0px solid  rgb(39, 77, 105) ;\n"
"    background-color: rgb(14, 16, 20);\n"
"color: #FFF;\n"
"border-radius: 10px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"}\n"
"")
        self.WordsInSubjectLine.setPlaceholderText("")
        self.WordsInSubjectLine.setObjectName("WordsInSubjectLine")
        self.horizontalLayout_3.addWidget(self.WordsInSubjectLine)
        self.gridLayout.addWidget(self.widget_6, 1, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.fromWhoLine = QtWidgets.QLineEdit(self.widget_5)
        self.fromWhoLine.setMinimumSize(QtCore.QSize(0, 21))
        self.fromWhoLine.setMaximumSize(QtCore.QSize(16777215, 31))
        self.fromWhoLine.setStyleSheet("QLineEdit{\n"
"border: 0px solid  rgb(39, 77, 105) ;\n"
"    background-color: rgb(14, 16, 20);\n"
"color: #FFF;\n"
"border-radius: 10px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"}\n"
"")
        self.fromWhoLine.setPlaceholderText("")
        self.fromWhoLine.setObjectName("fromWhoLine")
        self.horizontalLayout_2.addWidget(self.fromWhoLine)
        self.gridLayout.addWidget(self.widget_5, 0, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.WordsInAttachLine = QtWidgets.QLineEdit(self.widget_8)
        self.WordsInAttachLine.setMinimumSize(QtCore.QSize(0, 21))
        self.WordsInAttachLine.setMaximumSize(QtCore.QSize(16777215, 31))
        self.WordsInAttachLine.setStyleSheet("QLineEdit{\n"
"border: 0px solid  rgb(39, 77, 105) ;\n"
"    background-color: rgb(14, 16, 20);\n"
"color: #FFF;\n"
"border-radius: 10px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"}\n"
"")
        self.WordsInAttachLine.setPlaceholderText("")
        self.WordsInAttachLine.setObjectName("WordsInAttachLine")
        self.horizontalLayout_5.addWidget(self.WordsInAttachLine)
        self.gridLayout.addWidget(self.widget_8, 3, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.WordsInTextLine = QtWidgets.QLineEdit(self.widget_7)
        self.WordsInTextLine.setMinimumSize(QtCore.QSize(0, 21))
        self.WordsInTextLine.setMaximumSize(QtCore.QSize(16777215, 31))
        self.WordsInTextLine.setStyleSheet("QLineEdit{\n"
"border: 0px solid  rgb(39, 77, 105) ;\n"
"    background-color: rgb(14, 16, 20);\n"
"color: #FFF;\n"
"border-radius: 10px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"}\n"
"")
        self.WordsInTextLine.setPlaceholderText("")
        self.WordsInTextLine.setObjectName("WordsInTextLine")
        self.horizontalLayout_4.addWidget(self.WordsInTextLine)
        self.gridLayout.addWidget(self.widget_7, 2, 0, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_9.setStyleSheet("outline: 0px;")
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.dateEdit = QtWidgets.QDateEdit(self.widget_9)
        self.dateEdit.setMinimumSize(QtCore.QSize(331, 31))
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"    color: rgb(202, 206, 216);\n"
"    font-size: 14px;\n"
"    border: 0px solid  rgb(39, 77, 105) ;\n"
"    background-color: rgb(14, 16, 20);\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 20px;\n"
"}\n"
"\n"
"QDateEdit::drop-down \n"
"{;\n"
"    margin-left: -12px;\n"
"    margin-top: 2px;\n"
"    background-image: url(:/Pngs/Assets/ICLight/chevron-down.png);\n"
"    border: 0px solid red;\n"
"}\n"
"/*\n"
"QDateEdit QAbstracctItemView: enabled {\n"
"    \n"
"    background-color: rgb(35, 41, 51);\n"
"    color: rgb(179, 203, 231);\n"
"}*/\n"
"\n"
"QCalendarWidget QToolButton {\n"
"      /*height: 60px;\n"
"      width: 150px;*/\n"
"      color: white;\n"
"      font-size: 14px;\n"
"      icon-size: 16px, 16px;\n"
"      background-color:transparent;\n"
"  }\n"
"  QCalendarWidget QMenu {\n"
"      /*width: 150px;*/\n"
"      left: 20px;\n"
"      color: white;\n"
"      font-size: 14px;\n"
"      background-color: rgb(100, 100, 120);\n"
"  }\n"
"  QCalendarWidget QSpinBox { \n"
"      /*width: 50px; */\n"
"      font-size: 14px; \n"
"      color: white; \n"
"      background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #cccccc, stop: 1 #333333); \n"
"      selection-background-color: rgb(136, 136, 136);\n"
"      selection-color: rgb(255, 255, 255);\n"
"  }\n"
"  QCalendarWidget QSpinBox::up-button { subcontrol-origin: border;  subcontrol-position: top right;  width:25px; }\n"
"  QCalendarWidget QSpinBox::down-button {subcontrol-origin: border; subcontrol-position: bottom right;  width:25px;}\n"
"  QCalendarWidget QSpinBox::up-arrow { width:20px;  height:20px; }\n"
"  QCalendarWidget QSpinBox::down-arrow { width:20px;  height:20px; }\n"
"   \n"
"  /* header row */\n"
"  QCalendarWidget QWidget { alternate-background-color: rgb(58, 65, 98); }\n"
"   \n"
"  /* normal days */\n"
"  QCalendarWidget QAbstractItemView:enabled \n"
"  {\n"
"      font-size: 16px;  \n"
"      color: rgb(180, 180, 180);  \n"
"      background-color: rgb(35, 41, 51);  \n"
"      selection-background-color: rgb(55, 61, 100);  \n"
"      selection-color: rgb(0, 255, 0); \n"
"  }\n"
"   \n"
"  /* days in other months */\n"
"  /* navigation bar */\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar\n"
"{ \n"
"  background-color: rgb(37, 42, 50); \n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView:disabled \n"
"{ \n"
"color: rgb(64, 64, 64); \n"
"}\n"
"")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_6.addWidget(self.dateEdit)
        self.mailWorkSearchButton = QtWidgets.QPushButton(self.widget_9)
        self.mailWorkSearchButton.setMinimumSize(QtCore.QSize(200, 30))
        self.mailWorkSearchButton.setStyleSheet("QPushButton {\n"
"    color: rgb(166, 177, 211);\n"
"    background-color: rgb(38, 45, 58);\n"
"    border-left: 1px solid rgb(57, 79, 100);\n"
"    border-right: 1px solid rgb(51, 54, 60);    \n"
"    border-bottom: 3px solid rgb(28, 31, 46);\n"
"\n"
"    font-size: 16px;\n"
"    font: \"Copperplate Gothic Light\";\n"
"\n"
"    border-radius: 10px\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(25, 45, 64);\n"
"    border-left: 2px solid rgb(37, 46, 53);\n"
"    border-right: 2px solid rgb(31, 34, 40);    \n"
"    border-bottom: 3px solid rgb(18, 21, 26);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(20, 25, 34);\n"
"    border-left: 2px solid rgb(5, 26, 33);\n"
"    border-right: 2px solid rgb(5, 24, 30);    \n"
"    border-bottom: 3px solid rgb(5, 21, 26);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mailWorkSearchButton.setIcon(icon)
        self.mailWorkSearchButton.setObjectName("mailWorkSearchButton")
        self.horizontalLayout_6.addWidget(self.mailWorkSearchButton)
        self.gridLayout.addWidget(self.widget_9, 4, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(10, 320, 741, 361))
        self.widget_2.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(27, 32, 40);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(77, 87, 99);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(107, 117, 139);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(117, 135, 150);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(37, 42, 50);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"/*QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}*/\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(47, 52, 60);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(37, 42, 50);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"/*QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}*/\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color:  rgb(47, 52, 60);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.mailList = QtWidgets.QListWidget(self.widget_2)
        self.mailList.setGeometry(QtCore.QRect(10, 0, 271, 361))
        self.mailList.setStyleSheet("QListWidget\n"
"{\n"
"border : 0px solid black;\n"
"border-radius: 20px;\n"
"background : rgb(12, 14, 18);\n"
"padding: 6px;\n"
"outline: 0px;\n"
"font-size: 18px;\n"
"}\n"
" QListView::item:selected\n"
"{\n"
"border : 2px solid rgb(21, 25, 31);\n"
"background : rgb(41, 49, 61);\n"
"}\n"
"\n"
"QListView::item {\n"
"    color: rgb(202, 206, 216);\n"
"    background-color:rgb(21, 25, 31);\n"
"    border-radius: 10px;\n"
"    padding: 12px;\n"
"    margin: 5px\n"
"}\n"
"\n"
"/*QListWidget QScrollBar\n"
"{\n"
"background : rgb(33, 39, 48);\n"
"border: 2px solid red;\n"
"border-radius: 10px;\n"
"}\n"
"QListWidget QScrollBar::handle\n"
"{\n"
"background : rgb(91, 100, 105);\n"
"}\n"
"\n"
"QListWidget QScrollBar::handle::pressed\n"
"{\n"
"background : rgb(107, 117, 127);\n"
"}\n"
"QListView  QScrollBar::down-arrow:vertical {               \n"
"\n"
"    height: 40px; \n"
"    width: 40px  \n"
" }\n"
"*/")
        self.mailList.setAutoScroll(True)
        self.mailList.setProperty("showDropIndicator", False)
        self.mailList.setObjectName("mailList")
        self.widget_10 = QtWidgets.QWidget(self.widget_2)
        self.widget_10.setGeometry(QtCore.QRect(290, 10, 441, 351))
        self.widget_10.setObjectName("widget_10")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget_10)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 441, 137))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_12 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.searchedSubjectLine = QtWidgets.QLineEdit(self.widget_12)
        self.searchedSubjectLine.setMinimumSize(QtCore.QSize(221, 21))
        self.searchedSubjectLine.setStyleSheet("QLineEdit{\n"
"border: 0px solid  rgb(39, 77, 105) ;\n"
"    background-color: rgb(14, 16, 20);\n"
"color: #FFF;\n"
"border-radius: 10px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"}\n"
"")
        self.searchedSubjectLine.setReadOnly(True)
        self.searchedSubjectLine.setPlaceholderText("")
        self.searchedSubjectLine.setObjectName("searchedSubjectLine")
        self.horizontalLayout_8.addWidget(self.searchedSubjectLine)
        self.gridLayout_2.addWidget(self.widget_12, 1, 0, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.searchedFromWhoLine = QtWidgets.QLineEdit(self.widget_11)
        self.searchedFromWhoLine.setMinimumSize(QtCore.QSize(221, 21))
        self.searchedFromWhoLine.setStyleSheet("QLineEdit{\n"
"border: 0px solid  rgb(39, 77, 105) ;\n"
"    background-color: rgb(14, 16, 20);\n"
"color: #FFF;\n"
"border-radius: 10px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"}\n"
"")
        self.searchedFromWhoLine.setReadOnly(True)
        self.searchedFromWhoLine.setPlaceholderText("")
        self.searchedFromWhoLine.setObjectName("searchedFromWhoLine")
        self.horizontalLayout_7.addWidget(self.searchedFromWhoLine)
        self.gridLayout_2.addWidget(self.widget_11, 0, 0, 1, 1)
        self.widget_13 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.searchedDateEdit = QtWidgets.QDateEdit(self.widget_13)
        self.searchedDateEdit.setStyleSheet("QDateEdit {\n"
"    color: rgb(202, 206, 216);\n"
"    font-size: 14px;\n"
"    border: 0px solid  rgb(39, 77, 105) ;\n"
"    background-color: rgb(14, 16, 20);\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 20px;\n"
"}")
        self.searchedDateEdit.setReadOnly(True)
        self.searchedDateEdit.setCalendarPopup(False)
        self.searchedDateEdit.setObjectName("searchedDateEdit")
        self.horizontalLayout_9.addWidget(self.searchedDateEdit)
        self.gridLayout_2.addWidget(self.widget_13, 2, 0, 1, 1)
        self.textMailBrowser = QtWidgets.QTextBrowser(self.widget_10)
        self.textMailBrowser.setGeometry(QtCore.QRect(0, 130, 441, 211))
        self.textMailBrowser.setStyleSheet("QTextBrowser {\n"
"    color: rgb(202, 206, 216);\n"
"    background-color: rgb(35, 41, 51);\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"}")
        self.textMailBrowser.setObjectName("textMailBrowser")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 771, 31))
        self.widget_3.setStyleSheet("background-color: rgb(35, 41, 51);")
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(670, -10, 91, 51))
        self.widget_4.setStyleSheet("QPushButton {\n"
"    border: 2px solid transparent;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: rgb(20, 25, 34);\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mailWorkCollapseButton = QtWidgets.QPushButton(self.widget_4)
        self.mailWorkCollapseButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mailWorkCollapseButton.setIcon(icon1)
        self.mailWorkCollapseButton.setIconSize(QtCore.QSize(22, 22))
        self.mailWorkCollapseButton.setObjectName("mailWorkCollapseButton")
        self.horizontalLayout.addWidget(self.mailWorkCollapseButton)
        self.mailWorkCloseButton = QtWidgets.QPushButton(self.widget_4)
        self.mailWorkCloseButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mailWorkCloseButton.setIcon(icon2)
        self.mailWorkCloseButton.setIconSize(QtCore.QSize(22, 22))
        self.mailWorkCloseButton.setObjectName("mailWorkCloseButton")
        self.horizontalLayout.addWidget(self.mailWorkCloseButton)
        self.mailWorkCloseButton.raise_()
        self.mailWorkCollapseButton.raise_()
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 18))
        self.label.setStyleSheet("color: rgb(145, 160, 187);\n"
"font: \"Copperplate Gothic Light\";\n"
"font-size: 14px;")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "Поиск"))
        self.label_10.setText(_translate("Form", "Со словами в заголовке: "))
        self.label_8.setText(_translate("Form", "От кого:"))
        self.label_12.setText(_translate("Form", "Со словом в названии приложения к письму: "))
        self.label_11.setText(_translate("Form", "Со словами в тексте:"))
        self.label_13.setText(_translate("Form", "Дата получения: "))
        self.mailWorkSearchButton.setText(_translate("Form", "  Поиск"))
        self.label_16.setText(_translate("Form", "Тема:"))
        self.label_14.setText(_translate("Form", "От кого:"))
        self.label_15.setText(_translate("Form", "Дата получения: "))
        self.textMailBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8.50909pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.50909pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("Form", "Работа с письмами"))
import auto_res_rc
