# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LetterList.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(752, 371)
        Form.setStyleSheet("background-color: rgb(21, 25, 31);\n"
"font: \"Copperplate Gothic Light\";")
        self.mailListTriggerListTable = QtWidgets.QTableView(Form)
        self.mailListTriggerListTable.setGeometry(QtCore.QRect(20, 40, 711, 321))
        self.mailListTriggerListTable.setStyleSheet("QTableView {\n"
"         Color: white; /* text color in the table */\n"
"         Gridline-color: black; /*The inner frame color*/\n"
"         Background-color: rgb(33, 39, 48); /* background color in the table*/\n"
"    alternate-background-color: rgb(42, 50, 62);\n"
"         Selection-color: white; /* The text color of the selected area*/\n"
"         Selection-background-color: rgb(84, 89, 97); /*The background color of the selected area*/\n"
"    border: 2px groove rgb(12, 14, 17);\n"
"    border-radius: 30px;\n"
"    padding: 2px 4px;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    color: white;\n"
"    font: bold 10pt;\n"
"         Background-color: rgb(50, 70, 90);/*Set the background color of the header blank area*/\n"
"    border: 0px solid rgb(144, 144, 144);\n"
"    border: 0px solid rgb(191,191,191);\n"
"    border-left-color: rgba(255, 255, 255, 0);\n"
"    border-top-color: rgba(255, 255, 255, 0);\n"
"    border-radius:10px;\n"
"    min-height:29px;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(27, 32, 40);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(77, 87, 99);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(107, 117, 139);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(117, 135, 150);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(37, 42, 50);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"/*QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}*/\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(47, 52, 60);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(37, 42, 50);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"/*QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}*/\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color:  rgb(47, 52, 60);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"")
        self.mailListTriggerListTable.setObjectName("mailListTriggerListTable")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 761, 31))
        self.widget_2.setStyleSheet("background-color: rgb(35, 41, 51);")
        self.widget_2.setObjectName("widget_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(650, -10, 101, 51))
        self.widget_4.setStyleSheet("QPushButton {\n"
"    border: 2px solid transparent;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: rgb(20, 25, 34);\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mailListTriggerCollapseButton = QtWidgets.QPushButton(self.widget_4)
        self.mailListTriggerCollapseButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mailListTriggerCollapseButton.setIcon(icon)
        self.mailListTriggerCollapseButton.setIconSize(QtCore.QSize(22, 22))
        self.mailListTriggerCollapseButton.setObjectName("mailListTriggerCollapseButton")
        self.horizontalLayout.addWidget(self.mailListTriggerCollapseButton)
        self.mailListTriggerCloseButton = QtWidgets.QPushButton(self.widget_4)
        self.mailListTriggerCloseButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mailListTriggerCloseButton.setIcon(icon1)
        self.mailListTriggerCloseButton.setIconSize(QtCore.QSize(22, 22))
        self.mailListTriggerCloseButton.setObjectName("mailListTriggerCloseButton")
        self.horizontalLayout.addWidget(self.mailListTriggerCloseButton)
        self.mailListTriggerCloseButton.raise_()
        self.mailListTriggerCollapseButton.raise_()
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 18))
        self.label.setStyleSheet("color: rgb(145, 160, 187);\n"
"font: \"Copperplate Gothic Light\";\n"
"font-size: 14px;")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Важные письма"))
import auto_res_rc
