# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(587, 601)
        Form.setMinimumSize(QtCore.QSize(587, 601))
        Form.setMaximumSize(QtCore.QSize(587, 601))
        Form.setStyleSheet("background-color: rgb(21, 25, 31);\n"
"font: \"Copperplate Gothic Light\";")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 40, 567, 551))
        self.widget.setMinimumSize(QtCore.QSize(567, 531))
        self.widget.setMaximumSize(QtCore.QSize(1000, 1000))
        self.widget.setObjectName("widget")
        self.settingsChangeUserButton = QtWidgets.QPushButton(self.widget)
        self.settingsChangeUserButton.setGeometry(QtCore.QRect(20, 10, 531, 41))
        self.settingsChangeUserButton.setStyleSheet("QPushButton {\n"
"    color: rgb(166, 177, 211);\n"
"    background-color: rgb(38, 45, 58);\n"
"    border-left: 1px solid rgb(57, 79, 100);\n"
"    border-right: 1px solid rgb(51, 54, 60);    \n"
"    border-bottom: 3px solid rgb(28, 31, 46);\n"
"\n"
"    font-size: 16px;\n"
"    font: \"Copperplate Gothic Light\";\n"
"\n"
"    border-radius: 10px\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(25, 45, 64);\n"
"    border-left: 2px solid rgb(37, 46, 53);\n"
"    border-right: 2px solid rgb(31, 34, 40);    \n"
"    border-bottom: 3px solid rgb(18, 21, 26);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(20, 25, 34);\n"
"    border-left: 2px solid rgb(5, 26, 33);\n"
"    border-right: 2px solid rgb(5, 24, 30);    \n"
"    border-bottom: 3px solid rgb(5, 21, 26);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/corner-left-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsChangeUserButton.setIcon(icon)
        self.settingsChangeUserButton.setObjectName("settingsChangeUserButton")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(20, 70, 531, 151))
        self.widget_3.setMinimumSize(QtCore.QSize(521, 151))
        self.widget_3.setMaximumSize(QtCore.QSize(531, 151))
        self.widget_3.setObjectName("widget_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 531, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.showHideWidgetChecker = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.showHideWidgetChecker.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showHideWidgetChecker.setStyleSheet("QCheckBox{\n"
"color: rgb(202, 206, 216);\n"
"font-size: 14px;\n"
"font: \"Copperplate Gothic Light\";\n"
"}\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"border : 2px solid rgb(79, 117, 145);\n"
"width : 20px;\n"
"height : 20px;\n"
"border-radius : 10px;\n"
"}\n"
"\n"
"\n"
"QCheckBox::hover {\n"
"    color: #9ebad6\n"
"}\n"
"\n"
"\n"
"QCheckBox::hover::checked {\n"
"    border: solid #232933;\n"
"}\n"
"/*\n"
"QCheckBox:hover::unchecked {\n"
"    border: solid rgb(79, 117, 145);\n"
"}\n"
"\n"
"\n"
"QCheckBox:indicator: {\n"
"    border: 4px\n"
"}\n"
"\n"
"QCheckBox:indicator:unchecked:hover {\n"
"    color:#576e84\n"
"}\n"
"*/\n"
"\n"
"QCheckBox::indicator::checked\n"
"{\n"
"    image: url(:/Pngs/Assets/ICLight/check.png);\n"
"}\n"
"")
        self.showHideWidgetChecker.setText("")
        self.showHideWidgetChecker.setObjectName("showHideWidgetChecker")
        self.gridLayout.addWidget(self.showHideWidgetChecker, 2, 1, 1, 1)
        self.windowsStartChecker = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.windowsStartChecker.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.windowsStartChecker.setStyleSheet("QCheckBox{\n"
"color: rgb(202, 206, 216);\n"
"font-size: 14px;\n"
"font: \"Copperplate Gothic Light\";\n"
"}\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"border : 2px solid rgb(79, 117, 145);\n"
"width : 20px;\n"
"height : 20px;\n"
"border-radius : 10px;\n"
"}\n"
"\n"
"\n"
"QCheckBox::hover {\n"
"    color: #9ebad6\n"
"}\n"
"\n"
"\n"
"QCheckBox::hover::checked {\n"
"    border: solid #232933;\n"
"}\n"
"\n"
"QCheckBox::indicator::checked\n"
"{\n"
"    image: url(:/Pngs/Assets/ICLight/check.png);\n"
"}\n"
"")
        self.windowsStartChecker.setText("")
        self.windowsStartChecker.setObjectName("windowsStartChecker")
        self.gridLayout.addWidget(self.windowsStartChecker, 1, 1, 1, 1)
        self.rememberMeChecker = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.rememberMeChecker.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rememberMeChecker.setStyleSheet("QCheckBox{\n"
"color: rgb(202, 206, 216);\n"
"font-size: 14px;\n"
"font: \"Copperplate Gothic Light\";\n"
"}\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"border : 2px solid rgb(79, 117, 145);\n"
"width : 20px;\n"
"height : 20px;\n"
"border-radius : 10px;\n"
"}\n"
"\n"
"\n"
"QCheckBox::hover {\n"
"    color: #9ebad6\n"
"}\n"
"\n"
"\n"
"QCheckBox::hover::checked {\n"
"    border: solid #232933;\n"
"}\n"
"/*\n"
"QCheckBox:hover::unchecked {\n"
"    border: solid rgb(79, 117, 145);\n"
"}\n"
"\n"
"\n"
"QCheckBox:indicator: {\n"
"    border: 4px\n"
"}\n"
"\n"
"QCheckBox:indicator:unchecked:hover {\n"
"    color:#576e84\n"
"}\n"
"*/\n"
"\n"
"QCheckBox::indicator::checked\n"
"{\n"
"    image: url(:/Pngs/Assets/ICLight/check.png);\n"
"}\n"
"")
        self.rememberMeChecker.setText("")
        self.rememberMeChecker.setChecked(True)
        self.rememberMeChecker.setObjectName("rememberMeChecker")
        self.gridLayout.addWidget(self.rememberMeChecker, 0, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setGeometry(QtCore.QRect(20, 220, 531, 251))
        self.widget_5.setStyleSheet("QLineEdit{\n"
"border: 2px solid  rgb(39, 77, 105) ;\n"
"color: #FFF;\n"
"border-radius: 10px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(75, 130, 160);    \n"
"  background-color: rgb(27,40,65);\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 2px solid rgb(39, 77, 105);\n"
"    border-radius: 10px;\n"
"    padding: 1px 20px 3px 5px;\n"
"    min-width: 6em;\n"
"    color: rgb(202, 206, 216);\n"
"    font-size: 14px;\n"
"    font: \"Copperplate Gothic Light\";\n"
"}\n"
"\n"
"QComboBox::drop-down \n"
"{;\n"
"    margin-left: -10px;\n"
"    margin-top: 2px;\n"
"    background-image: url(:/Pngs/Assets/ICLight/chevron-down.png);\n"
"    border: 0px;\n"
"}\n"
"\n"
"\n"
"QLabel {\n"
"    font: \"Copperplate Gothic Light\";\n"
"    color: rgb(202, 206, 216);\n"
"    font-size: 16px;\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget_5)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 531, 234))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.whereComboBox_1 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.whereComboBox_1.setStyleSheet("")
        self.whereComboBox_1.setObjectName("whereComboBox_1")
        self.whereComboBox_1.addItem("")
        self.whereComboBox_1.addItem("")
        self.whereComboBox_1.addItem("")
        self.whereComboBox_1.addItem("")
        self.gridLayout_2.addWidget(self.whereComboBox_1, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 2, 0, 1, 1)
        self.whereComboBox_4 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.whereComboBox_4.setStyleSheet("")
        self.whereComboBox_4.setObjectName("whereComboBox_4")
        self.whereComboBox_4.addItem("")
        self.whereComboBox_4.addItem("")
        self.whereComboBox_4.addItem("")
        self.whereComboBox_4.addItem("")
        self.gridLayout_2.addWidget(self.whereComboBox_4, 4, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lineEdit_5.setStyleSheet("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 5, 0, 1, 1)
        self.whereComboBox_6 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.whereComboBox_6.setStyleSheet("")
        self.whereComboBox_6.setObjectName("whereComboBox_6")
        self.whereComboBox_6.addItem("")
        self.whereComboBox_6.addItem("")
        self.whereComboBox_6.addItem("")
        self.whereComboBox_6.addItem("")
        self.gridLayout_2.addWidget(self.whereComboBox_6, 6, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lineEdit_4.setStyleSheet("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 4, 0, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_1.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lineEdit_1.setStyleSheet("")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout_2.addWidget(self.lineEdit_1, 1, 0, 1, 1)
        self.whereComboBox_5 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.whereComboBox_5.setStyleSheet("")
        self.whereComboBox_5.setObjectName("whereComboBox_5")
        self.whereComboBox_5.addItem("")
        self.whereComboBox_5.addItem("")
        self.whereComboBox_5.addItem("")
        self.whereComboBox_5.addItem("")
        self.gridLayout_2.addWidget(self.whereComboBox_5, 5, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 3, 0, 1, 1)
        self.whereComboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.whereComboBox_3.setStyleSheet("")
        self.whereComboBox_3.setObjectName("whereComboBox_3")
        self.whereComboBox_3.addItem("")
        self.whereComboBox_3.addItem("")
        self.whereComboBox_3.addItem("")
        self.whereComboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.whereComboBox_3, 3, 1, 1, 1)
        self.whereComboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.whereComboBox_2.setStyleSheet("")
        self.whereComboBox_2.setObjectName("whereComboBox_2")
        self.whereComboBox_2.addItem("")
        self.whereComboBox_2.addItem("")
        self.whereComboBox_2.addItem("")
        self.whereComboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.whereComboBox_2, 2, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(16777215, 31))
        self.lineEdit_6.setStyleSheet("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setStyleSheet("")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout_2.addWidget(self.label_1, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.colorComboBox_1 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.colorComboBox_1.setMinimumSize(QtCore.QSize(143, 0))
        self.colorComboBox_1.setMaximumSize(QtCore.QSize(121, 29))
        self.colorComboBox_1.setToolTipDuration(-5)
        self.colorComboBox_1.setStyleSheet("")
        self.colorComboBox_1.setObjectName("colorComboBox_1")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Custom/Assets/Custom/combo_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox_1.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Custom/Assets/Custom/combo_Green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox_1.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Custom/Assets/Custom/combo_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox_1.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Custom/Assets/Custom/combo_yellow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox_1.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Custom/Assets/Custom/combo_azure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox_1.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Custom/Assets/Custom/combo_purple.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox_1.addItem(icon6, "")
        self.gridLayout_2.addWidget(self.colorComboBox_1, 1, 2, 1, 1)
        self.colorComboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.colorComboBox_2.setMinimumSize(QtCore.QSize(143, 0))
        self.colorComboBox_2.setMaximumSize(QtCore.QSize(121, 29))
        self.colorComboBox_2.setToolTipDuration(-5)
        self.colorComboBox_2.setStyleSheet("")
        self.colorComboBox_2.setObjectName("colorComboBox_2")
        self.colorComboBox_2.addItem(icon1, "")
        self.colorComboBox_2.addItem(icon2, "")
        self.colorComboBox_2.addItem(icon3, "")
        self.colorComboBox_2.addItem(icon4, "")
        self.colorComboBox_2.addItem(icon5, "")
        self.colorComboBox_2.addItem(icon6, "")
        self.gridLayout_2.addWidget(self.colorComboBox_2, 2, 2, 1, 1)
        self.colorComboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.colorComboBox_3.setMinimumSize(QtCore.QSize(143, 0))
        self.colorComboBox_3.setMaximumSize(QtCore.QSize(121, 29))
        self.colorComboBox_3.setToolTipDuration(-5)
        self.colorComboBox_3.setStyleSheet("")
        self.colorComboBox_3.setObjectName("colorComboBox_3")
        self.colorComboBox_3.addItem(icon1, "")
        self.colorComboBox_3.addItem(icon2, "")
        self.colorComboBox_3.addItem(icon3, "")
        self.colorComboBox_3.addItem(icon4, "")
        self.colorComboBox_3.addItem(icon5, "")
        self.colorComboBox_3.addItem(icon6, "")
        self.gridLayout_2.addWidget(self.colorComboBox_3, 3, 2, 1, 1)
        self.colorComboBox_4 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.colorComboBox_4.setMinimumSize(QtCore.QSize(143, 0))
        self.colorComboBox_4.setMaximumSize(QtCore.QSize(121, 29))
        self.colorComboBox_4.setToolTipDuration(-5)
        self.colorComboBox_4.setStyleSheet("")
        self.colorComboBox_4.setObjectName("colorComboBox_4")
        self.colorComboBox_4.addItem(icon1, "")
        self.colorComboBox_4.addItem(icon2, "")
        self.colorComboBox_4.addItem(icon3, "")
        self.colorComboBox_4.addItem(icon4, "")
        self.colorComboBox_4.addItem(icon5, "")
        self.colorComboBox_4.addItem(icon6, "")
        self.gridLayout_2.addWidget(self.colorComboBox_4, 4, 2, 1, 1)
        self.colorComboBox_5 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.colorComboBox_5.setMinimumSize(QtCore.QSize(143, 0))
        self.colorComboBox_5.setMaximumSize(QtCore.QSize(121, 29))
        self.colorComboBox_5.setToolTipDuration(-5)
        self.colorComboBox_5.setStyleSheet("")
        self.colorComboBox_5.setObjectName("colorComboBox_5")
        self.colorComboBox_5.addItem(icon1, "")
        self.colorComboBox_5.addItem(icon2, "")
        self.colorComboBox_5.addItem(icon3, "")
        self.colorComboBox_5.addItem(icon4, "")
        self.colorComboBox_5.addItem(icon5, "")
        self.colorComboBox_5.addItem(icon6, "")
        self.gridLayout_2.addWidget(self.colorComboBox_5, 5, 2, 1, 1)
        self.colorComboBox_6 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.colorComboBox_6.setMinimumSize(QtCore.QSize(143, 0))
        self.colorComboBox_6.setMaximumSize(QtCore.QSize(121, 29))
        self.colorComboBox_6.setToolTipDuration(-5)
        self.colorComboBox_6.setStyleSheet("")
        self.colorComboBox_6.setObjectName("colorComboBox_6")
        self.colorComboBox_6.addItem(icon1, "")
        self.colorComboBox_6.addItem(icon2, "")
        self.colorComboBox_6.addItem(icon3, "")
        self.colorComboBox_6.addItem(icon4, "")
        self.colorComboBox_6.addItem(icon5, "")
        self.colorComboBox_6.addItem(icon6, "")
        self.gridLayout_2.addWidget(self.colorComboBox_6, 6, 2, 1, 1)
        self.settingsMailWorkButton = QtWidgets.QPushButton(self.widget)
        self.settingsMailWorkButton.setGeometry(QtCore.QRect(30, 480, 241, 51))
        self.settingsMailWorkButton.setStyleSheet("QPushButton {\n"
"    color: rgb(166, 177, 211);\n"
"    background-color: rgb(38, 45, 58);\n"
"    border-left: 1px solid rgb(57, 79, 100);\n"
"    border-right: 1px solid rgb(51, 54, 60);    \n"
"    border-bottom: 3px solid rgb(28, 31, 46);\n"
"\n"
"    font-size: 16px;\n"
"    font: \"Copperplate Gothic Light\";\n"
"\n"
"    border-radius: 10px\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(25, 45, 64);\n"
"    border-left: 2px solid rgb(37, 46, 53);\n"
"    border-right: 2px solid rgb(31, 34, 40);    \n"
"    border-bottom: 3px solid rgb(18, 21, 26);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(20, 25, 34);\n"
"    border-left: 2px solid rgb(5, 26, 33);\n"
"    border-right: 2px solid rgb(5, 24, 30);    \n"
"    border-bottom: 3px solid rgb(5, 21, 26);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/align-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsMailWorkButton.setIcon(icon7)
        self.settingsMailWorkButton.setObjectName("settingsMailWorkButton")
        self.settingsSaveAndExitButton = QtWidgets.QPushButton(self.widget)
        self.settingsSaveAndExitButton.setGeometry(QtCore.QRect(380, 480, 161, 51))
        self.settingsSaveAndExitButton.setStyleSheet("QPushButton {\n"
"    color: rgb(166, 177, 211);\n"
"    background-color: rgb(38, 45, 58);\n"
"    border-left: 1px solid rgb(57, 79, 100);\n"
"    border-right: 1px solid rgb(51, 54, 60);    \n"
"    border-bottom: 3px solid rgb(28, 31, 46);\n"
"\n"
"    font-size: 14px;\n"
"    font: \"Copperplate Gothic Light\";\n"
"\n"
"    border-radius: 10px\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(25, 45, 64);\n"
"    border-left: 2px solid rgb(37, 46, 53);\n"
"    border-right: 2px solid rgb(31, 34, 40);    \n"
"    border-bottom: 3px solid rgb(18, 21, 26);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(20, 25, 34);\n"
"    border-left: 2px solid rgb(5, 26, 33);\n"
"    border-right: 2px solid rgb(5, 24, 30);    \n"
"    border-bottom: 3px solid rgb(5, 21, 26);\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsSaveAndExitButton.setIcon(icon8)
        self.settingsSaveAndExitButton.setObjectName("settingsSaveAndExitButton")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(-10, 0, 611, 31))
        self.widget_2.setStyleSheet("background-color: rgb(35, 41, 51);")
        self.widget_2.setObjectName("widget_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(480, -10, 121, 41))
        self.widget_4.setStyleSheet("QPushButton {\n"
"    border: 2px solid transparent;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: rgb(20, 25, 34);\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settingsCollapseButton = QtWidgets.QPushButton(self.widget_4)
        self.settingsCollapseButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsCollapseButton.setIcon(icon9)
        self.settingsCollapseButton.setIconSize(QtCore.QSize(22, 22))
        self.settingsCollapseButton.setObjectName("settingsCollapseButton")
        self.horizontalLayout.addWidget(self.settingsCollapseButton)
        self.settingsCloseButton = QtWidgets.QPushButton(self.widget_4)
        self.settingsCloseButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsCloseButton.setIcon(icon10)
        self.settingsCloseButton.setIconSize(QtCore.QSize(22, 22))
        self.settingsCloseButton.setObjectName("settingsCloseButton")
        self.horizontalLayout.addWidget(self.settingsCloseButton)
        self.settingsCloseButton.raise_()
        self.settingsCollapseButton.raise_()
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 131, 18))
        self.label_4.setStyleSheet("color: rgb(145, 160, 187);\n"
"font: \"Copperplate Gothic Light\";\n"
"font-size: 14px;")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        self.whereComboBox_1.setCurrentIndex(-1)
        self.whereComboBox_4.setCurrentIndex(-1)
        self.whereComboBox_6.setCurrentIndex(-1)
        self.whereComboBox_5.setCurrentIndex(-1)
        self.whereComboBox_3.setCurrentIndex(-1)
        self.whereComboBox_2.setCurrentIndex(-1)
        self.colorComboBox_1.setCurrentIndex(0)
        self.colorComboBox_2.setCurrentIndex(1)
        self.colorComboBox_3.setCurrentIndex(2)
        self.colorComboBox_4.setCurrentIndex(3)
        self.colorComboBox_5.setCurrentIndex(4)
        self.colorComboBox_6.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.settingsChangeUserButton.setText(_translate("Form", "  Сменить пользователя"))
        self.label_8.setText(_translate("Form", "Показать/спрятать Виджет"))
        self.label_7.setText(_translate("Form", "Запускать с Windows"))
        self.label_6.setText(_translate("Form", "Запомнить меня"))
        self.whereComboBox_1.setItemText(0, _translate("Form", "Отправитель"))
        self.whereComboBox_1.setItemText(1, _translate("Form", "Заголовок письма"))
        self.whereComboBox_1.setItemText(2, _translate("Form", "Текст письма"))
        self.whereComboBox_1.setItemText(3, _translate("Form", "Название вложений"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Введите ключевое слово"))
        self.whereComboBox_4.setItemText(0, _translate("Form", "Отправитель"))
        self.whereComboBox_4.setItemText(1, _translate("Form", "Заголовок письма"))
        self.whereComboBox_4.setItemText(2, _translate("Form", "Текст письма"))
        self.whereComboBox_4.setItemText(3, _translate("Form", "Название вложений"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "Введите ключевое слово"))
        self.whereComboBox_6.setItemText(0, _translate("Form", "Отправитель"))
        self.whereComboBox_6.setItemText(1, _translate("Form", "Заголовок письма"))
        self.whereComboBox_6.setItemText(2, _translate("Form", "Текст письма"))
        self.whereComboBox_6.setItemText(3, _translate("Form", "Название вложений"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Введите ключевое слово"))
        self.lineEdit_1.setPlaceholderText(_translate("Form", "Введите ключевое слово"))
        self.whereComboBox_5.setItemText(0, _translate("Form", "Отправитель"))
        self.whereComboBox_5.setItemText(1, _translate("Form", "Заголовок письма"))
        self.whereComboBox_5.setItemText(2, _translate("Form", "Текст письма"))
        self.whereComboBox_5.setItemText(3, _translate("Form", "Название вложений"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Введите ключевое слово"))
        self.whereComboBox_3.setItemText(0, _translate("Form", "Отправитель"))
        self.whereComboBox_3.setItemText(1, _translate("Form", "Заголовок письма"))
        self.whereComboBox_3.setItemText(2, _translate("Form", "Текст письма"))
        self.whereComboBox_3.setItemText(3, _translate("Form", "Название вложений"))
        self.whereComboBox_2.setItemText(0, _translate("Form", "Отправитель"))
        self.whereComboBox_2.setItemText(1, _translate("Form", "Заголовок письма"))
        self.whereComboBox_2.setItemText(2, _translate("Form", "Текст письма"))
        self.whereComboBox_2.setItemText(3, _translate("Form", "Название вложений"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "Введите ключевое слово"))
        self.label.setText(_translate("Form", "Ключевое слово/email"))
        self.label_1.setText(_translate("Form", "Где искать"))
        self.label_2.setText(_translate("Form", "Цвет уведомления"))
        self.colorComboBox_1.setItemText(0, _translate("Form", "Красный"))
        self.colorComboBox_1.setItemText(1, _translate("Form", "Зеленый"))
        self.colorComboBox_1.setItemText(2, _translate("Form", "Синий"))
        self.colorComboBox_1.setItemText(3, _translate("Form", "Желтый"))
        self.colorComboBox_1.setItemText(4, _translate("Form", "Лазурный"))
        self.colorComboBox_1.setItemText(5, _translate("Form", "Фиолетовый"))
        self.colorComboBox_2.setItemText(0, _translate("Form", "Красный"))
        self.colorComboBox_2.setItemText(1, _translate("Form", "Зеленый"))
        self.colorComboBox_2.setItemText(2, _translate("Form", "Синий"))
        self.colorComboBox_2.setItemText(3, _translate("Form", "Желтый"))
        self.colorComboBox_2.setItemText(4, _translate("Form", "Лазурный"))
        self.colorComboBox_2.setItemText(5, _translate("Form", "Фиолетовый"))
        self.colorComboBox_3.setItemText(0, _translate("Form", "Красный"))
        self.colorComboBox_3.setItemText(1, _translate("Form", "Зеленый"))
        self.colorComboBox_3.setItemText(2, _translate("Form", "Синий"))
        self.colorComboBox_3.setItemText(3, _translate("Form", "Желтый"))
        self.colorComboBox_3.setItemText(4, _translate("Form", "Лазурный"))
        self.colorComboBox_3.setItemText(5, _translate("Form", "Фиолетовый"))
        self.colorComboBox_4.setItemText(0, _translate("Form", "Красный"))
        self.colorComboBox_4.setItemText(1, _translate("Form", "Зеленый"))
        self.colorComboBox_4.setItemText(2, _translate("Form", "Синий"))
        self.colorComboBox_4.setItemText(3, _translate("Form", "Желтый"))
        self.colorComboBox_4.setItemText(4, _translate("Form", "Лазурный"))
        self.colorComboBox_4.setItemText(5, _translate("Form", "Фиолетовый"))
        self.colorComboBox_5.setItemText(0, _translate("Form", "Красный"))
        self.colorComboBox_5.setItemText(1, _translate("Form", "Зеленый"))
        self.colorComboBox_5.setItemText(2, _translate("Form", "Синий"))
        self.colorComboBox_5.setItemText(3, _translate("Form", "Желтый"))
        self.colorComboBox_5.setItemText(4, _translate("Form", "Лазурный"))
        self.colorComboBox_5.setItemText(5, _translate("Form", "Фиолетовый"))
        self.colorComboBox_6.setItemText(0, _translate("Form", "Красный"))
        self.colorComboBox_6.setItemText(1, _translate("Form", "Зеленый"))
        self.colorComboBox_6.setItemText(2, _translate("Form", "Синий"))
        self.colorComboBox_6.setItemText(3, _translate("Form", "Желтый"))
        self.colorComboBox_6.setItemText(4, _translate("Form", "Лазурный"))
        self.colorComboBox_6.setItemText(5, _translate("Form", "Фиолетовый"))
        self.settingsMailWorkButton.setText(_translate("Form", "  Работа с письмами"))
        self.settingsSaveAndExitButton.setText(_translate("Form", "Сохранить и выйти"))
        self.label_4.setText(_translate("Form", "Настройки"))
import auto_res_rc
