# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SmallWidgetLamp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(250, 200)
        Form.setMinimumSize(QtCore.QSize(250, 200))
        Form.setMaximumSize(QtCore.QSize(250, 200))
        Form.setWindowOpacity(0.8)
        Form.setStyleSheet("background-color: rgb(44, 52, 65);")
        self.colorIndicator = QtWidgets.QLabel(Form)
        self.colorIndicator.setEnabled(True)
        self.colorIndicator.setGeometry(QtCore.QRect(20, 50, 101, 91))
        self.colorIndicator.setText("")
        self.colorIndicator.setPixmap(QtGui.QPixmap(":/Custom/Assets/Custom/red.png"))
        self.colorIndicator.setObjectName("colorIndicator")
        self.smallWidgetMailListButton = QtWidgets.QPushButton(Form)
        self.smallWidgetMailListButton.setGeometry(QtCore.QRect(170, 70, 41, 41))
        self.smallWidgetMailListButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid transparent;\n"
"    border-radius: 10px\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: rgb(20, 25, 34);\n"
"}")
        self.smallWidgetMailListButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Light/Assets/Light/mail.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.smallWidgetMailListButton.setIcon(icon)
        self.smallWidgetMailListButton.setIconSize(QtCore.QSize(36, 36))
        self.smallWidgetMailListButton.setObjectName("smallWidgetMailListButton")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(130, 0, 121, 61))
        self.widget.setStyleSheet("QPushButton {\n"
"    border: 2px solid transparent;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: rgb(20, 25, 34);\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.smallWidgetSettings = QtWidgets.QPushButton(self.widget)
        self.smallWidgetSettings.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Light/Assets/Light/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.smallWidgetSettings.setIcon(icon1)
        self.smallWidgetSettings.setIconSize(QtCore.QSize(20, 20))
        self.smallWidgetSettings.setObjectName("smallWidgetSettings")
        self.horizontalLayout.addWidget(self.smallWidgetSettings)
        self.smallWidgetCollapseButton = QtWidgets.QPushButton(self.widget)
        self.smallWidgetCollapseButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.smallWidgetCollapseButton.setIcon(icon2)
        self.smallWidgetCollapseButton.setIconSize(QtCore.QSize(22, 22))
        self.smallWidgetCollapseButton.setObjectName("smallWidgetCollapseButton")
        self.horizontalLayout.addWidget(self.smallWidgetCollapseButton)
        self.smallWidgetCloseButton = QtWidgets.QPushButton(self.widget)
        self.smallWidgetCloseButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Pngs/Assets/ICLight/x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.smallWidgetCloseButton.setIcon(icon3)
        self.smallWidgetCloseButton.setIconSize(QtCore.QSize(22, 22))
        self.smallWidgetCloseButton.setObjectName("smallWidgetCloseButton")
        self.horizontalLayout.addWidget(self.smallWidgetCloseButton)
        self.username = QtWidgets.QLabel(Form)
        self.username.setGeometry(QtCore.QRect(20, 160, 211, 21))
        self.username.setStyleSheet("color: rgb(202, 206, 216);\n"
"font-size: 14px;\n"
"font: \"Copperplate Gothic Light\";")
        self.username.setObjectName("username")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.username.setText(_translate("Form", "Почтовый ящик"))
import auto_res_rc
